export const mockEmployees = [
  {
    id: "1",
    name: "Priyanka Raut",
    employeeId: "345321231",
    department: "Design",
    designation: "UI/UX Designer",
    status: "Permanent",
  },
  {
    id: "2",
    name: "Saurabh Patil",
    employeeId: "987890345",
    department: "Development",
    designation: "PHP Developer",
    status: "Permanent",
  },
  {
    id: "3",
    name: "Violet Cowan",
    employeeId: "453367122",
    department: "Sales",
    designation: "Sales Manager",
    status: "Permanent",
  },
  {
    id: "4",
    name: "Aadesh Rathod",
    employeeId: "345321231",
    department: "Sales",
    designation: "BDM",
    status: "Permanent",
  },
  {
    id: "5",
    name: "Pratham Patne",
    employeeId: "453677881",
    department: "Design",
    designation: "Design Lead",
    status: "Permanent",
  },
  {
    id: "6",
    name: "Rushi Raut",
    employeeId: "009918765",
    department: "Development",
    designation: "Python Developer",
    status: "Permanent",
  },
  {
    id: "7",
    name: "Om Shinde",
    employeeId: "238870122",
    department: "Development",
    designation: "Sr. UI Developer",
    status: "Permanent",
  },
  {
    id: "8",
    name: "Sakshi Rayte",
    employeeId: "124335111",
    department: "PM",
    designation: "Project Manager",
    status: "Permanent",
  },
  {
    id: "9",
    name: "Tushita Salunkhe",
    employeeId: "435540099",
    department: "HR",
    designation: "HR Executive",
    status: "Permanent",
  },
  {
    id: "10",
    name: "Mayuri Rane",
    employeeId: "009812890",
    department: "Development",
    designation: "React JS Developer",
    status: "Permanent",
  },
  {
    id: "11",
    name: "Suraj Pawar",
    employeeId: "671190345",
    department: "Development",
    designation: "Node JS",
    status: "Permanent",
  },
  {
    id: "12",
    name: "Shivam Jagtap",
    employeeId: "091233412",
    department: "BA",
    designation: "Business Analyst",
    status: "Permanent",
  },
];